### ISSUE TITLE
在有些页面上恢复的时候会添加空行

### ISSUE THREAD

**Issue by hellodword** [imlinhanchao/script-restore-translate#1]
谢谢你的脚本。

使用时发现一些页面上有些问题，例如添加空行、改变布局

[例子](https://medium.com/@sonus21/the-good-bad-and-ugly-of-go-errors-cd6841b02ee8) 

![1](https://user-images.githubusercontent.com/46193371/88507013-f910c700-d00d-11ea-8571-e471db07ed66.png)
![2](https://user-images.githubusercontent.com/46193371/88507016-fada8a80-d00d-11ea-9438-bc85ad398da7.png)
![3](https://user-images.githubusercontent.com/46193371/88507149-59076d80-d00e-11ea-8ea8-2676219fa098.png)

**Comment by imlinhanchao** [comment]
哈哈，這個是已知問題。不過不好解決。暫時沒想到什麽好辦法。你有空也可以研究看看，有辦法解決的話可以提個 Pull Request 。

**Comment by hellodword** [comment]
> 哈哈，這個是已知問題。不過不好解決。暫時沒想到什麽好辦法。你有空也可以研究看看，有辦法解決的話可以提個 Pull Request 。

确实不太好解决😂

**Comment by dnknn** [comment]
@imlinhanchao 
跟这个页面冲突了, 导致页面元素无法显示, 排查很久发现是你脚本在作怪哈.👇
https://www.google.com/chrome/
